resolver: lts-8.17

# Local packages, usually specified by relative directory name
packages:
- '.'

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
